import type { AutomationEase, RoleTask } from "@/lib/workflow-types";

type WorkflowTaskSeed = {
  id: string;
  role: string;
  task: string;
  workflowName: string;
  automationEase: AutomationEase;
  category: string;
  whyAutomatable?: string;
  safeApproach?: string;
  humanReviewNeeded?: string[];
  notRecommendedToAutomateFully?: string[];
  successMetrics?: string[];
};

const humanReviewDefaults = [
  "Review AI-assisted drafts before internal or client-facing use.",
  "Confirm facts, deadlines, owners, and operational commitments.",
  "Escalate legal, tax, compliance, security, or financial judgment questions to the appropriate human owner.",
];

const notAutomateDefaults = [
  "Do not use public AI tools with client names, financial records, payroll data, tax records, credentials, or confidential information.",
  "Do not make automatic business decisions, system changes, accounting record changes, access approvals, tax advice, or client commitments.",
];

const metricsByCategory: Record<string, string[]> = {
  "AI use-case governance": [
    "Number of AI workflow ideas reviewed",
    "Sensitive-data risks identified before pilot",
    "Time to approve, reject, or escalate proposed use cases",
  ],
  "Internal communication": [
    "Time spent drafting internal updates",
    "Manager edit rate",
    "Staff questions or clarification requests reduced",
  ],
  "Operational reporting": [
    "Time spent creating weekly summaries",
    "Manual follow-ups reduced",
    "Missed blockers identified earlier",
  ],
  "Service improvement": [
    "Number of improvement ideas converted into action plans",
    "Time from issue discovery to draft plan",
    "Leadership review time",
  ],
  "Vendor review": [
    "Time spent comparing vendors",
    "Criteria coverage",
    "Decision-maker review time",
  ],
  "Decision support boundary": [
    "Time saved preparing decision packets",
    "Escalation rate",
    "Human approval completion rate",
  ],
  "Process documentation": [
    "Number of SOP drafts created",
    "Time to create first draft",
    "Manager edit rate",
  ],
  "Checklist standardization": [
    "Checklist completion rate",
    "Rework reduced",
    "Time spent preparing recurring checklists",
  ],
  "Meeting follow-up": [
    "Time spent summarizing notes",
    "Action items captured",
    "Missed follow-ups reduced",
  ],
  "Bottleneck reporting": [
    "Recurring blockers identified",
    "Time spent preparing bottleneck notes",
    "Manager review time",
  ],
  "Client onboarding": [
    "Time to prepare onboarding materials",
    "Missing steps reduced",
    "Client handoff rework rate",
  ],
  "Client service triage": [
    "Time to summarize client requests",
    "Routing accuracy",
    "Escalation rate",
  ],
  "Client communication draft": [
    "Draft preparation time",
    "Human edit rate",
    "Client response time when used after approval",
  ],
  "Client information checklist": [
    "Missing-information follow-ups reduced",
    "Time to prepare request checklists",
    "Staff review time",
  ],
  "Accounting review support": [
    "Time spent summarizing cleanup notes",
    "Manager review time",
    "Rework rate",
  ],
  "Month-end support": [
    "Checklist completion rate",
    "Close task cycle time",
    "Review exceptions found",
  ],
  "Tax workflow support": [
    "Missing-document follow-ups reduced",
    "Time to prepare tax intake checklist",
    "Staff review time",
  ],
  "Advisory meeting support": [
    "Time from meeting notes to action plan",
    "Action items captured",
    "Review and edit rate",
  ],
  "Advisory reporting support": [
    "Time spent drafting commentary",
    "Human revision rate",
    "Client-ready issues caught before delivery",
  ],
  "Administrative coordination": [
    "Manual reminder preparation time",
    "Recurring tasks completed on schedule",
    "Staff clarification requests reduced",
  ],
  "Request routing": [
    "Requests routed correctly",
    "Time to assign an owner",
    "Escalation accuracy",
  ],
  "Sales follow-up": [
    "Time to draft follow-up notes",
    "Next steps captured",
    "Human edit rate",
  ],
  "Lead qualification support": [
    "Lead notes reviewed",
    "Fit criteria completed",
    "Review time before outreach or proposal",
  ],
  "People operations": [
    "Onboarding checklist completion",
    "Training feedback summarized",
    "HR review time",
  ],
  "IT operations": [
    "Tickets summarized",
    "Recurring issues identified",
    "Time to draft troubleshooting notes",
  ],
  "Security governance": [
    "AI tool requests reviewed",
    "Access review reminders completed",
    "Sensitive-data risks escalated",
  ],
};

const roleAliases: Record<string, string[]> = {
  "Owner / Managing Partner": ["owner", "managing partner", "founder", "partner", "ceo", "president"],
  "Operations Manager / Practice Manager": ["operations manager", "practice manager", "ops manager", "coo", "operations"],
  "Client Services Manager": ["client services", "client service", "account manager", "customer success"],
  Bookkeeper: ["bookkeeper", "bookkeeping", "accounting clerk", "staff accountant"],
  "Tax Manager / Tax Admin": ["tax manager", "tax admin", "tax administrator", "tax operations", "tax"],
  "Fractional CFO / Advisory Lead": ["fractional cfo", "cfo", "advisory lead", "advisor", "advisory"],
  "Administrative / Office Manager": ["admin", "administrative", "office manager", "office administrator"],
  "Sales / Business Development": ["sales", "business development", "bd", "revenue", "growth"],
  "HR / People Operations": ["hr", "human resources", "people operations", "people ops", "talent"],
  "IT / Security / Systems Admin": ["it", "security", "systems admin", "system administrator", "technology"],
};

function createTask(seed: WorkflowTaskSeed): RoleTask {
  return {
    ...seed,
    whyAutomatable:
      seed.whyAutomatable ??
      `${seed.task} is usually repetitive, text-heavy, checklist-based, or easy to structure before a qualified person reviews the output.`,
    safeApproach:
      seed.safeApproach ??
      `Start with sanitized examples in an approved business workspace. Use AI to draft, summarize, categorize, or structure the work, then keep the final step with a human owner.`,
    humanReviewNeeded: seed.humanReviewNeeded ?? humanReviewDefaults,
    notRecommendedToAutomateFully:
      seed.notRecommendedToAutomateFully ?? notAutomateDefaults,
    successMetrics:
      seed.successMetrics ?? metricsByCategory[seed.category] ?? [
        "Manual time before and after the workflow change",
        "Human review time",
        "Error or rework rate",
      ],
  };
}

const taskSeeds: WorkflowTaskSeed[] = [
  {
    id: "owner-ai-use-case-review",
    role: "Owner / Managing Partner",
    task: "Reviewing and prioritizing internal AI use-case ideas",
    workflowName: "AI Use-Case Review Workflow",
    automationEase: "High",
    category: "AI use-case governance",
  },
  {
    id: "owner-firm-announcement-drafts",
    role: "Owner / Managing Partner",
    task: "Drafting internal updates or firm announcements",
    workflowName: "Internal Firm Update Drafting Workflow",
    automationEase: "High",
    category: "Internal communication",
  },
  {
    id: "owner-operational-bottleneck-summary",
    role: "Owner / Managing Partner",
    task: "Summarizing operational bottlenecks from team notes",
    workflowName: "Operational Bottleneck Summary Workflow",
    automationEase: "High",
    category: "Operational reporting",
  },
  {
    id: "owner-service-improvement-plan",
    role: "Owner / Managing Partner",
    task: "Preparing service improvement plans",
    workflowName: "Service Improvement Planning Workflow",
    automationEase: "Medium",
    category: "Service improvement",
  },
  {
    id: "owner-client-service-trends",
    role: "Owner / Managing Partner",
    task: "Reviewing client service trends",
    workflowName: "Client Service Trend Review Workflow",
    automationEase: "Medium",
    category: "Service improvement",
  },
  {
    id: "owner-vendor-comparison",
    role: "Owner / Managing Partner",
    task: "Comparing software or vendor options",
    workflowName: "Vendor Comparison Brief Workflow",
    automationEase: "Medium",
    category: "Vendor review",
  },
  {
    id: "owner-staffing-decisions",
    role: "Owner / Managing Partner",
    task: "Making staffing decisions",
    workflowName: "Staffing Decision Packet Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not automate staffing decisions.",
      "Use AI only to organize approved, non-sensitive inputs for human leadership review.",
    ],
  },
  {
    id: "owner-pricing-decisions",
    role: "Owner / Managing Partner",
    task: "Final pricing decisions",
    workflowName: "Pricing Decision Support Brief Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not automate final pricing commitments.",
      "Do not claim guaranteed ROI from a website preview.",
    ],
  },
  {
    id: "owner-formal-determinations",
    role: "Owner / Managing Partner",
    task: "Formal legal, tax, or compliance determinations",
    workflowName: "Professional Determination Escalation Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not use AI to provide legal, tax, or compliance certification advice.",
      "Use AI only to prepare questions for the appropriate professional reviewer.",
    ],
  },
  {
    id: "ops-weekly-status-summaries",
    role: "Operations Manager / Practice Manager",
    task: "Creating weekly internal status summaries",
    workflowName: "Weekly Internal Status Summary Workflow",
    automationEase: "High",
    category: "Operational reporting",
  },
  {
    id: "ops-sop-drafts",
    role: "Operations Manager / Practice Manager",
    task: "Turning messy process notes into SOP drafts",
    workflowName: "SOP Drafting Workflow",
    automationEase: "High",
    category: "Process documentation",
  },
  {
    id: "ops-recurring-task-checklists",
    role: "Operations Manager / Practice Manager",
    task: "Building recurring task checklists",
    workflowName: "Recurring Task Checklist Workflow",
    automationEase: "High",
    category: "Checklist standardization",
  },
  {
    id: "ops-meeting-follow-up-summaries",
    role: "Operations Manager / Practice Manager",
    task: "Preparing meeting follow-up summaries",
    workflowName: "Meeting Notes to Action Plan Workflow",
    automationEase: "High",
    category: "Meeting follow-up",
  },
  {
    id: "ops-team-bottleneck-prioritization",
    role: "Operations Manager / Practice Manager",
    task: "Prioritizing team bottlenecks",
    workflowName: "Team Bottleneck Reporting Workflow",
    automationEase: "Medium",
    category: "Bottleneck reporting",
  },
  {
    id: "ops-client-onboarding-standardization",
    role: "Operations Manager / Practice Manager",
    task: "Standardizing client onboarding workflows",
    workflowName: "Client Onboarding Standardization Workflow",
    automationEase: "Medium",
    category: "Client onboarding",
  },
  {
    id: "ops-internal-handoff-notes",
    role: "Operations Manager / Practice Manager",
    task: "Preparing internal handoff notes",
    workflowName: "Internal Handoff Note Workflow",
    automationEase: "Medium",
    category: "Process documentation",
  },
  {
    id: "ops-auto-record-changes",
    role: "Operations Manager / Practice Manager",
    task: "Automatically changing project records across systems",
    workflowName: "Project Record Change Review Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not automatically change project records across systems without manager approval.",
      "Start with draft updates or exception reports that a manager reviews.",
    ],
  },
  {
    id: "ops-unreviewed-approvals",
    role: "Operations Manager / Practice Manager",
    task: "Making approval decisions without manager review",
    workflowName: "Approval Review Checklist Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not automate approval decisions without manager review.",
      "Use AI only to organize the information needed for approval.",
    ],
  },
  {
    id: "ops-complex-cross-system-automation",
    role: "Operations Manager / Practice Manager",
    task: "Complex cross-system workflow automation",
    workflowName: "Cross-System Automation Readiness Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not start with complex integrations before validating the workflow manually.",
      "Pilot the process with human review before connecting production systems.",
    ],
  },
  {
    id: "client-request-summaries",
    role: "Client Services Manager",
    task: "Summarizing client requests for internal review",
    workflowName: "Client Request Summary Workflow",
    automationEase: "High",
    category: "Client service triage",
  },
  {
    id: "client-follow-up-drafts",
    role: "Client Services Manager",
    task: "Drafting client follow-up messages for human review",
    workflowName: "Client Follow-Up Draft Workflow",
    automationEase: "High",
    category: "Client communication draft",
  },
  {
    id: "client-missing-info-checklists",
    role: "Client Services Manager",
    task: "Creating missing-information checklists",
    workflowName: "Missing-Information Checklist Workflow",
    automationEase: "High",
    category: "Client information checklist",
  },
  {
    id: "client-status-update-drafts",
    role: "Client Services Manager",
    task: "Preparing client status update drafts",
    workflowName: "Client Status Update Draft Workflow",
    automationEase: "High",
    category: "Client communication draft",
  },
  {
    id: "client-scope-creep-review",
    role: "Client Services Manager",
    task: "Identifying possible scope creep",
    workflowName: "Scope Creep Review Notes Workflow",
    automationEase: "Medium",
    category: "Client service triage",
  },
  {
    id: "client-request-routing",
    role: "Client Services Manager",
    task: "Routing client requests to the right internal owner",
    workflowName: "Client Request Routing Workflow",
    automationEase: "Medium",
    category: "Request routing",
  },
  {
    id: "client-quality-review-notes",
    role: "Client Services Manager",
    task: "Creating service quality review notes",
    workflowName: "Service Quality Review Notes Workflow",
    automationEase: "Medium",
    category: "Service improvement",
  },
  {
    id: "client-auto-email-send",
    role: "Client Services Manager",
    task: "Sending client emails automatically",
    workflowName: "Client Email Human Review Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not send client emails automatically without human review.",
      "Use AI only to prepare drafts, summaries, and checklists.",
    ],
  },
  {
    id: "client-auto-commitments",
    role: "Client Services Manager",
    task: "Making client commitments automatically",
    workflowName: "Client Commitment Review Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not let AI make client commitments, deadlines, pricing promises, or scope decisions.",
      "Keep commitments with an authorized human reviewer.",
    ],
  },
  {
    id: "client-sensitive-public-ai",
    role: "Client Services Manager",
    task: "Handling sensitive client data in public AI tools",
    workflowName: "Sensitive Data Guardrail Workflow",
    automationEase: "Low",
    category: "Security governance",
    notRecommendedToAutomateFully: [
      "Do not upload sensitive client data to public AI tools.",
      "Use sanitized examples, client-owned platforms, access controls, and retention rules.",
    ],
  },
  {
    id: "bookkeeper-document-request-checklists",
    role: "Bookkeeper",
    task: "Creating document request checklists",
    workflowName: "Bookkeeping Document Request Checklist Workflow",
    automationEase: "High",
    category: "Client information checklist",
  },
  {
    id: "bookkeeper-cleanup-note-summaries",
    role: "Bookkeeper",
    task: "Summarizing bookkeeping cleanup notes",
    workflowName: "Bookkeeping Cleanup Note Summary Workflow",
    automationEase: "High",
    category: "Accounting review support",
  },
  {
    id: "bookkeeper-clarification-questions",
    role: "Bookkeeper",
    task: "Drafting clarification questions for clients",
    workflowName: "Client Clarification Question Draft Workflow",
    automationEase: "High",
    category: "Client communication draft",
  },
  {
    id: "bookkeeper-transaction-review-summary",
    role: "Bookkeeper",
    task: "Turning transaction review notes into internal summaries",
    workflowName: "Transaction Review Summary Workflow",
    automationEase: "High",
    category: "Accounting review support",
  },
  {
    id: "bookkeeper-month-end-close-checklists",
    role: "Bookkeeper",
    task: "Preparing month-end close checklists",
    workflowName: "Month-End Close Checklist Workflow",
    automationEase: "Medium",
    category: "Month-end support",
  },
  {
    id: "bookkeeper-plain-english-issues",
    role: "Bookkeeper",
    task: "Explaining bookkeeping issues in plain English",
    workflowName: "Plain-English Bookkeeping Explanation Workflow",
    automationEase: "Medium",
    category: "Accounting review support",
  },
  {
    id: "bookkeeper-manager-review-notes",
    role: "Bookkeeper",
    task: "Creating internal review notes for manager approval",
    workflowName: "Manager Review Note Workflow",
    automationEase: "Medium",
    category: "Accounting review support",
  },
  {
    id: "bookkeeper-auto-reconciliation",
    role: "Bookkeeper",
    task: "Reconciling transactions automatically",
    workflowName: "Reconciliation Exception Review Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not reconcile transactions automatically from a website preview or public AI tool.",
      "Use AI only to draft explanations or organize exception notes for human review.",
    ],
  },
  {
    id: "bookkeeper-auto-accounting-changes",
    role: "Bookkeeper",
    task: "Changing accounting records automatically",
    workflowName: "Accounting Record Change Review Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not let AI automatically change accounting records.",
      "Keep all accounting record changes under approved system controls and human review.",
    ],
  },
  {
    id: "bookkeeper-live-sensitive-records",
    role: "Bookkeeper",
    task: "Reviewing live bank statements or payroll data in public AI tools",
    workflowName: "Sensitive Financial Data Guardrail Workflow",
    automationEase: "Low",
    category: "Security governance",
    notRecommendedToAutomateFully: [
      "Do not upload bank statements, payroll data, or client financial records to public AI tools.",
      "Use sanitized examples inside approved business environments for any pilot.",
    ],
  },
  {
    id: "tax-intake-checklists",
    role: "Tax Manager / Tax Admin",
    task: "Preparing tax-prep intake checklists",
    workflowName: "Tax-Prep Intake Checklist Workflow",
    automationEase: "High",
    category: "Tax workflow support",
  },
  {
    id: "tax-missing-document-reminders",
    role: "Tax Manager / Tax Admin",
    task: "Drafting missing-document reminders",
    workflowName: "Missing-Document Reminder Draft Workflow",
    automationEase: "High",
    category: "Tax workflow support",
  },
  {
    id: "tax-client-note-summaries",
    role: "Tax Manager / Tax Admin",
    task: "Summarizing client-provided notes for internal review",
    workflowName: "Client Note Summary for Tax Review Workflow",
    automationEase: "High",
    category: "Tax workflow support",
  },
  {
    id: "tax-staff-review-checklists",
    role: "Tax Manager / Tax Admin",
    task: "Creating staff review checklists",
    workflowName: "Tax Staff Review Checklist Workflow",
    automationEase: "High",
    category: "Tax workflow support",
  },
  {
    id: "tax-workload-notes",
    role: "Tax Manager / Tax Admin",
    task: "Organizing tax season workload notes",
    workflowName: "Tax Season Workload Summary Workflow",
    automationEase: "Medium",
    category: "Operational reporting",
  },
  {
    id: "tax-client-safe-explanation-drafts",
    role: "Tax Manager / Tax Admin",
    task: "Preparing client-safe explanation drafts",
    workflowName: "Client-Safe Tax Explanation Draft Workflow",
    automationEase: "Medium",
    category: "Client communication draft",
  },
  {
    id: "tax-internal-deadline-reminders",
    role: "Tax Manager / Tax Admin",
    task: "Creating internal deadline reminders",
    workflowName: "Internal Tax Deadline Reminder Workflow",
    automationEase: "Medium",
    category: "Administrative coordination",
  },
  {
    id: "tax-advice-answers",
    role: "Tax Manager / Tax Admin",
    task: "Answering tax advice questions",
    workflowName: "Tax Advice Escalation Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not automate tax advice.",
      "Use AI only to organize questions and draft non-advisory explanations for qualified review.",
    ],
  },
  {
    id: "tax-actual-return-review",
    role: "Tax Manager / Tax Admin",
    task: "Reviewing actual tax returns",
    workflowName: "Tax Return Review Boundary Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not upload actual tax returns into public AI tools.",
      "Do not rely on AI for final tax return review or filing decisions.",
    ],
  },
  {
    id: "tax-filing-decisions",
    role: "Tax Manager / Tax Admin",
    task: "Making filing decisions",
    workflowName: "Filing Decision Human Review Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not automate filing decisions.",
      "Keep filing decisions with qualified tax professionals and documented approval.",
    ],
  },
  {
    id: "tax-sensitive-documents-public-ai",
    role: "Tax Manager / Tax Admin",
    task: "Processing sensitive tax documents in public AI tools",
    workflowName: "Sensitive Tax Data Guardrail Workflow",
    automationEase: "Low",
    category: "Security governance",
    notRecommendedToAutomateFully: [
      "Do not process sensitive tax documents in public AI tools.",
      "Use approved business environments, access controls, sanitized examples, and retention rules.",
    ],
  },
  {
    id: "cfo-meeting-notes-action-items",
    role: "Fractional CFO / Advisory Lead",
    task: "Turning meeting notes into action items",
    workflowName: "Advisory Meeting Notes to Action Items Workflow",
    automationEase: "High",
    category: "Advisory meeting support",
  },
  {
    id: "cfo-advisory-follow-up-drafts",
    role: "Fractional CFO / Advisory Lead",
    task: "Drafting advisory follow-up emails for review",
    workflowName: "Advisory Follow-Up Draft Workflow",
    automationEase: "High",
    category: "Client communication draft",
  },
  {
    id: "cfo-client-question-lists",
    role: "Fractional CFO / Advisory Lead",
    task: "Creating client question lists before meetings",
    workflowName: "Pre-Meeting Client Question List Workflow",
    automationEase: "High",
    category: "Advisory meeting support",
  },
  {
    id: "cfo-owner-conversation-briefs",
    role: "Fractional CFO / Advisory Lead",
    task: "Summarizing owner conversations into internal briefs",
    workflowName: "Owner Conversation Brief Workflow",
    automationEase: "High",
    category: "Advisory meeting support",
  },
  {
    id: "cfo-monthly-business-themes",
    role: "Fractional CFO / Advisory Lead",
    task: "Summarizing monthly business themes",
    workflowName: "Monthly Business Theme Summary Workflow",
    automationEase: "Medium",
    category: "Advisory reporting support",
  },
  {
    id: "cfo-board-style-commentary-drafts",
    role: "Fractional CFO / Advisory Lead",
    task: "Preparing board-style commentary drafts",
    workflowName: "Board-Style Commentary Draft Workflow",
    automationEase: "Medium",
    category: "Advisory reporting support",
  },
  {
    id: "cfo-advisory-priority-organization",
    role: "Fractional CFO / Advisory Lead",
    task: "Organizing client advisory priorities",
    workflowName: "Advisory Priority Organization Workflow",
    automationEase: "Medium",
    category: "Advisory meeting support",
  },
  {
    id: "cfo-forecasting-without-validated-data",
    role: "Fractional CFO / Advisory Lead",
    task: "Forecasting without validated financial data",
    workflowName: "Forecasting Input Readiness Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not produce forecasts without validated financial data and professional review.",
      "Use AI only to structure assumptions and identify missing inputs.",
    ],
  },
  {
    id: "cfo-unreviewed-financial-recommendations",
    role: "Fractional CFO / Advisory Lead",
    task: "Making financial recommendations without human review",
    workflowName: "Financial Recommendation Review Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not automate financial recommendations without expert review.",
      "Use AI only to prepare internal drafts, questions, and summaries.",
    ],
  },
  {
    id: "cfo-final-board-reports",
    role: "Fractional CFO / Advisory Lead",
    task: "Producing final board reports automatically",
    workflowName: "Board Report Human Review Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not generate final board reports automatically.",
      "Keep final reporting under qualified human review and approved source data.",
    ],
  },
  {
    id: "admin-follow-up-reminders",
    role: "Administrative / Office Manager",
    task: "Scheduling follow-up reminders",
    workflowName: "Follow-Up Reminder Scheduling Workflow",
    automationEase: "High",
    category: "Administrative coordination",
  },
  {
    id: "admin-intake-checklists",
    role: "Administrative / Office Manager",
    task: "Creating intake checklists",
    workflowName: "Administrative Intake Checklist Workflow",
    automationEase: "High",
    category: "Checklist standardization",
  },
  {
    id: "admin-internal-announcements",
    role: "Administrative / Office Manager",
    task: "Drafting internal announcements",
    workflowName: "Internal Announcement Draft Workflow",
    automationEase: "High",
    category: "Internal communication",
  },
  {
    id: "admin-meeting-notes-task-lists",
    role: "Administrative / Office Manager",
    task: "Organizing meeting notes into task lists",
    workflowName: "Meeting Notes to Task List Workflow",
    automationEase: "High",
    category: "Meeting follow-up",
  },
  {
    id: "admin-internal-request-routing",
    role: "Administrative / Office Manager",
    task: "Routing internal requests",
    workflowName: "Internal Request Routing Workflow",
    automationEase: "Medium",
    category: "Request routing",
  },
  {
    id: "admin-onboarding-packets",
    role: "Administrative / Office Manager",
    task: "Preparing onboarding packets",
    workflowName: "Onboarding Packet Preparation Workflow",
    automationEase: "Medium",
    category: "People operations",
  },
  {
    id: "admin-recurring-process-checklists",
    role: "Administrative / Office Manager",
    task: "Maintaining recurring process checklists",
    workflowName: "Recurring Process Checklist Workflow",
    automationEase: "Medium",
    category: "Checklist standardization",
  },
  {
    id: "admin-auto-access-approval",
    role: "Administrative / Office Manager",
    task: "Approving access requests automatically",
    workflowName: "Access Request Review Workflow",
    automationEase: "Low",
    category: "Security governance",
    notRecommendedToAutomateFully: [
      "Do not approve access requests automatically.",
      "Use AI only to prepare reminders or checklists for authorized reviewers.",
    ],
  },
  {
    id: "admin-hr-payroll-public-ai",
    role: "Administrative / Office Manager",
    task: "Handling HR or payroll-sensitive records in public AI tools",
    workflowName: "Sensitive HR and Payroll Data Guardrail Workflow",
    automationEase: "Low",
    category: "Security governance",
    notRecommendedToAutomateFully: [
      "Do not handle HR or payroll-sensitive records in public AI tools.",
      "Use approved business environments and sanitized examples only.",
    ],
  },
  {
    id: "admin-policy-decisions",
    role: "Administrative / Office Manager",
    task: "Making policy decisions",
    workflowName: "Policy Decision Review Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not automate policy decisions.",
      "Use AI only for draft language and issue lists reviewed by leadership.",
    ],
  },
  {
    id: "sales-prospect-note-summaries",
    role: "Sales / Business Development",
    task: "Summarizing prospect notes",
    workflowName: "Prospect Note Summary Workflow",
    automationEase: "High",
    category: "Sales follow-up",
  },
  {
    id: "sales-follow-up-email-drafts",
    role: "Sales / Business Development",
    task: "Drafting follow-up emails for review",
    workflowName: "Sales Follow-Up Draft Workflow",
    automationEase: "High",
    category: "Sales follow-up",
  },
  {
    id: "sales-discovery-call-prep",
    role: "Sales / Business Development",
    task: "Creating discovery call prep notes",
    workflowName: "Discovery Call Prep Workflow",
    automationEase: "High",
    category: "Sales follow-up",
  },
  {
    id: "sales-call-notes-next-steps",
    role: "Sales / Business Development",
    task: "Turning call notes into next-step summaries",
    workflowName: "Sales Call Notes to Next Steps Workflow",
    automationEase: "High",
    category: "Sales follow-up",
  },
  {
    id: "sales-lead-fit-prioritization",
    role: "Sales / Business Development",
    task: "Prioritizing leads based on fit",
    workflowName: "Lead Fit Prioritization Workflow",
    automationEase: "Medium",
    category: "Lead qualification support",
  },
  {
    id: "sales-proposal-outlines",
    role: "Sales / Business Development",
    task: "Drafting proposal outlines",
    workflowName: "Proposal Outline Draft Workflow",
    automationEase: "Medium",
    category: "Sales follow-up",
  },
  {
    id: "sales-objection-handling-notes",
    role: "Sales / Business Development",
    task: "Creating objection-handling notes",
    workflowName: "Objection-Handling Notes Workflow",
    automationEase: "Medium",
    category: "Sales follow-up",
  },
  {
    id: "sales-auto-proposal-send",
    role: "Sales / Business Development",
    task: "Sending proposals automatically",
    workflowName: "Proposal Human Review Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not send proposals automatically.",
      "Keep proposal scope, pricing, and commitments under human review.",
    ],
  },
  {
    id: "sales-pricing-commitments",
    role: "Sales / Business Development",
    task: "Making pricing commitments",
    workflowName: "Pricing Commitment Review Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not automate pricing commitments.",
      "Use AI only to organize approved assumptions for review.",
    ],
  },
  {
    id: "sales-guaranteed-roi-claims",
    role: "Sales / Business Development",
    task: "Claiming guaranteed ROI",
    workflowName: "ROI Claim Review Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not claim guaranteed ROI.",
      "Estimate ROI from agreed assumptions and validate it during a pilot.",
    ],
  },
  {
    id: "hr-onboarding-checklists",
    role: "HR / People Operations",
    task: "Drafting onboarding checklists",
    workflowName: "Employee Onboarding Checklist Workflow",
    automationEase: "High",
    category: "People operations",
  },
  {
    id: "hr-training-feedback-summaries",
    role: "HR / People Operations",
    task: "Summarizing training feedback",
    workflowName: "Training Feedback Summary Workflow",
    automationEase: "High",
    category: "People operations",
  },
  {
    id: "hr-internal-faq-drafts",
    role: "HR / People Operations",
    task: "Creating internal FAQ drafts",
    workflowName: "Internal HR FAQ Draft Workflow",
    automationEase: "High",
    category: "People operations",
  },
  {
    id: "hr-policy-reminder-drafts",
    role: "HR / People Operations",
    task: "Drafting policy reminder messages",
    workflowName: "Policy Reminder Draft Workflow",
    automationEase: "High",
    category: "Internal communication",
  },
  {
    id: "hr-performance-review-notes",
    role: "HR / People Operations",
    task: "Organizing performance review notes",
    workflowName: "Performance Review Note Organization Workflow",
    automationEase: "Medium",
    category: "People operations",
  },
  {
    id: "hr-training-plans",
    role: "HR / People Operations",
    task: "Creating training plans",
    workflowName: "Training Plan Draft Workflow",
    automationEase: "Medium",
    category: "People operations",
  },
  {
    id: "hr-employee-question-summaries",
    role: "HR / People Operations",
    task: "Summarizing employee questions",
    workflowName: "Employee Question Summary Workflow",
    automationEase: "Medium",
    category: "People operations",
  },
  {
    id: "hr-employment-decisions",
    role: "HR / People Operations",
    task: "Making employment decisions",
    workflowName: "Employment Decision Review Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not automate employment decisions.",
      "Use AI only to organize non-sensitive inputs for authorized HR review.",
    ],
  },
  {
    id: "hr-sensitive-records-public-ai",
    role: "HR / People Operations",
    task: "Handling sensitive employee records in public AI tools",
    workflowName: "Sensitive Employee Data Guardrail Workflow",
    automationEase: "Low",
    category: "Security governance",
    notRecommendedToAutomateFully: [
      "Do not put sensitive employee records into public AI tools.",
      "Use approved business environments, access controls, and retention rules.",
    ],
  },
  {
    id: "hr-final-policy-production",
    role: "HR / People Operations",
    task: "Producing final HR policy without review",
    workflowName: "HR Policy Human Review Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not produce final HR policy without review.",
      "Use AI only for draft language and issue lists approved by HR leadership.",
    ],
  },
  {
    id: "it-ticket-summaries",
    role: "IT / Security / Systems Admin",
    task: "Summarizing support tickets",
    workflowName: "Support Ticket Summary Workflow",
    automationEase: "High",
    category: "IT operations",
  },
  {
    id: "it-troubleshooting-checklists",
    role: "IT / Security / Systems Admin",
    task: "Creating internal troubleshooting checklists",
    workflowName: "Troubleshooting Checklist Workflow",
    automationEase: "High",
    category: "IT operations",
  },
  {
    id: "it-access-review-reminders",
    role: "IT / Security / Systems Admin",
    task: "Drafting access review reminders",
    workflowName: "Access Review Reminder Workflow",
    automationEase: "High",
    category: "Security governance",
  },
  {
    id: "it-software-rollout-notes",
    role: "IT / Security / Systems Admin",
    task: "Creating software rollout notes",
    workflowName: "Software Rollout Notes Workflow",
    automationEase: "High",
    category: "IT operations",
  },
  {
    id: "it-recurring-support-prioritization",
    role: "IT / Security / Systems Admin",
    task: "Prioritizing recurring support issues",
    workflowName: "Recurring Support Issue Prioritization Workflow",
    automationEase: "Medium",
    category: "IT operations",
  },
  {
    id: "it-ai-tool-request-review",
    role: "IT / Security / Systems Admin",
    task: "Reviewing AI tool requests",
    workflowName: "AI Tool Request Review Workflow",
    automationEase: "Medium",
    category: "Security governance",
  },
  {
    id: "it-security-awareness-reminders",
    role: "IT / Security / Systems Admin",
    task: "Creating internal security awareness reminders",
    workflowName: "Security Awareness Reminder Workflow",
    automationEase: "Medium",
    category: "Security governance",
  },
  {
    id: "it-auto-access-approval",
    role: "IT / Security / Systems Admin",
    task: "Auto-approving access",
    workflowName: "Access Approval Boundary Workflow",
    automationEase: "Low",
    category: "Security governance",
    notRecommendedToAutomateFully: [
      "Do not auto-approve access.",
      "Use AI only for reminder drafting, evidence collection, and reviewer checklists.",
    ],
  },
  {
    id: "it-auto-permission-changes",
    role: "IT / Security / Systems Admin",
    task: "Changing permissions automatically",
    workflowName: "Permission Change Human Approval Workflow",
    automationEase: "Low",
    category: "Security governance",
    notRecommendedToAutomateFully: [
      "Do not let AI change permissions automatically.",
      "Keep access changes inside approved identity systems with authorized human approval.",
    ],
  },
  {
    id: "it-credential-handling",
    role: "IT / Security / Systems Admin",
    task: "Handling credentials or secrets",
    workflowName: "Credential Handling Guardrail Workflow",
    automationEase: "Low",
    category: "Security governance",
    notRecommendedToAutomateFully: [
      "Do not enter credentials, private keys, API keys, or access tokens into AI tools.",
      "Use AI only for generic policy drafts or checklists without secrets.",
    ],
  },
  {
    id: "it-incident-response-decisions",
    role: "IT / Security / Systems Admin",
    task: "Making incident response decisions",
    workflowName: "Incident Response Escalation Workflow",
    automationEase: "Low",
    category: "Decision support boundary",
    notRecommendedToAutomateFully: [
      "Do not use this preview for incident response decisions.",
      "Escalate security incidents to the authorized response process and qualified experts.",
    ],
  },
];

export const workflowTasks: RoleTask[] = taskSeeds.map(createTask);

export function getRoleAliases(role: string) {
  return roleAliases[role] ?? [];
}

export function knownRoles() {
  return Object.keys(roleAliases);
}
